README.md

Cool program! Here's a quick start for getting it up and running on Mac. Treat as you see fit.

Add Mac OS X Quick Start to README

---

.gitignore
Cargo.lock

Commit Cargo.lock for reproducibility

---

cursive/src/main.rs
gtk/src/main.rs
qml/src/main.rs

New at rust, but still learning, so I decided to contribute the simplest way I know: apply clippy's advices on your repo!

a simple humble cargo clippy advised fixes

---

src/pass.rs

If you have multiple key identities in .gpg-id, then edit doesn't work

---

Cargo.lock
Cargo.toml
cursive/src/main.rs
src/pass.rs

Including a generate random password button.
Also added the generate random to the normal edit dialog.

Added a dialog for adding a new password file

---

qml/src/main.rs

Added in two if statements to avoid trying to access empty lists. When search yields no results the list will be empty instead of panicking.

Fix crash issues when search result is empty

---

cursive/res/nn.po
generate_pot.sh

Beware, I don't use my nynorsk daily but it should serve as a valid starting point.

Initial commit of Norwegian nynorsk translation

---

cursive/src/main.rs
cursive/src/wizard.rs

This fixes lots of clippy complaints, mostly by replacing if xxx.is_error() by match{} constructs.

Clippy fixes

---

cursive/build.rs
cursive/src/main.rs
cursive/src/wizard.rs
gtk/src/main.rs
qml/src/main.rs
src/pass.rs
src/pass/test.rs

Add a configuration option to the settings file that allows the user to configure the theme of the different password stores differently.

Support style config

---

cursive/src/helpers.rs
cursive/src/main.rs
gtk/src/main.rs
src/error.rs
src/pass.rs
src/pass/test.rs
src/signature.rs

implement Display for Error, so that error messages are nicely formated

---

src/pass.rs

instead write the index to file and update the head target to the commit oid.
This fixes #94

do not use reset when doing a commit

---

Cargo.lock
Cargo.toml
cursive/Cargo.toml
cursive/src/main.rs
cursive/src/wizard.rs
gtk/src/main.rs
src/pass.rs
src/signature.rs

also fixed some minor clippy feedback

update dependencies to latest version

---

cursive/res/de.po
cursive/res/fr.po
cursive/res/it.po
cursive/res/nb.po
cursive/res/nn.po
cursive/res/ripasso-cursive.pot
cursive/res/sv.po
generate_pot.sh

also improved the generate_pot.sh script so that it works better when adding new translations

update translation files

---

cursive/src/main.rs
src/crypto.rs
src/pass.rs
src/pass/test_helpers.rs

This can be useful if someone only uploads their gpg key to keybase for example.

menu option for importing a gpg cert from text

---

Cargo.lock
Cargo.toml
cursive/src/main.rs
src/crypto.rs
src/pass.rs
src/pass/test_helpers.rs
src/signature.rs

upgrade gpgme to latest version, and consider more than just expiry when checking if a key is usable.

remove direct usage of gpgme from signature.rs

---

src/pass.rs
src/pass/test.rs
src/pass/test_helpers.rs

if an encryption error happens, then make sure to clean up the file on disk that was created but not filled with any content

cleanup on encryption error

---

cursive/src/main.rs
cursive/src/wizard.rs
gtk/src/main.rs
qml/src/main.rs
src/crypto.rs
src/pass.rs
src/pass/test.rs
src/pass/test_helpers.rs
src/signature.rs

Motivation for this  PR is in this thread: https://users.rust-lang.org/t/to-string-vs-to-owned-for-string-literals/1441/6

use to_owned() instead of to_string() on string literals

---

src/pass.rs
src/tests/pass.rs

it disapears from the password list until ripasso is restarted

when adding a password and then searching for it

---

cursive/src/main.rs
src/pass.rs
src/signature.rs
src/tests/signature.rs
src/tests/test_helpers.rs

See this commit for reference
https://git.zx2c4.com/password-store/commit/?id=a271b43cbd76cc30406202c49041b552656538bd

Add support for comments in the .gpg-id file.

---

Cargo.lock
cursive/Cargo.toml
cursive/src/helpers.rs
cursive/src/main.rs

first we try the wayland copy buffer, and if that doesn't work we try the more generic clipboard crate

New strategy for copying stuff to the clipboard

---

.github/workflows/rust.yml
Cargo.lock
cursive/Cargo.toml
cursive/src/tests/main.rs
src/pass.rs
src/tests/pass.rs

then the path parameter didn't include the final '.gpg'

If a password was created without an initialized git repository

---

README.md

Adds install information to readme for installing TUI ripasso on alpine

update: add alpine install to readme

---

cursive/src/main.rs
cursive/src/tests/main.rs
gtk/src/main.rs
qml/src/main.rs
src/pass.rs
src/tests/pass.rs

This functions job was to replace the content of one PasswordStore object with the configuration of another, this strategy became more and more complicated, and instead we use a arc + mutex pattern to point to the currently active store

Removed the reset function

---

Cargo.lock
Cargo.toml
cursive/build.rs
cursive/res/de.po
cursive/res/fr.po
cursive/res/it.po
cursive/res/nb.po
cursive/res/nn.po
cursive/res/ripasso-cursive.pot
cursive/res/sv.po
cursive/src/main.rs
src/error.rs
src/pass.rs
src/tests/pass.rs

Relevant for feature request #242

support otpauth urls inside the secrets

---

.github/workflows/rust.yml
BUILD_INSTRUCTIONS.md
Cargo.lock
Cargo.toml
cursive/build.rs
cursive/src/main.rs
cursive/src/tests/main.rs
cursive/src/wizard.rs
gtk/src/main.rs
qml/src/main.rs
src/crypto.rs
src/error.rs
src/pass.rs
src/signature.rs
src/tests/crypto.rs
src/tests/pass.rs
src/tests/test_helpers.rs

Add support for the user to choose what pgp implementation that should be used, either gpgme or the new one that is sequoia.

Support pgp backend sequoia

---

src/pass.rs
src/tests/pass.rs

Fix the end position of otpauth URL string

Fix otpauth URL parsing

---

cursive/src/main.rs

Fix deadlock

---

Cargo.lock
cursive/Cargo.toml
cursive/src/helpers.rs

replace the clipboard crate with cli-clipboard

---

cursive/src/main.rs
src/error.rs

so that .lock() can be handled by ? easily

impl From<PoisonError> for Error

---

README.md

as the previous one seem to have died

replace meritbadge.herokuapp.com with img.shields.io

---

Cargo.toml

Fix e-mail address bracket
